# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "299a9a9f32a21f497dab810906d3fd09"
name = "wishlist-inspire"
handle = "wishlist-inspire-373"
application_url = "https://topic-mileage-disabled-dh.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "codecraft-team.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://topic-mileage-disabled-dh.trycloudflare.com/auth/callback",
  "https://topic-mileage-disabled-dh.trycloudflare.com/auth/shopify/callback",
  "https://topic-mileage-disabled-dh.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "https://ct-witnesses-maintain-protocol.trycloudflare.com/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "https://ct-witnesses-maintain-protocol.trycloudflare.com/webhooks/app/scopes_update"

[pos]
embedded = false
