name = "wishlist-icon"

uid = "23cc0911-4903-ae58-b04a-1a7627eee9a0470e04c9"

type = "theme"

[[blocks]]
name   = "Wishlist Button"
target = "product-card"         # or "product" if you prefer
path   = "blocks/wishlist-button.liquid"

[[blocks]]
name   = "Wishlist Page"
target = "page"
path   = "blocks/wishlist-page.liquid"


[[blocks]]
name   = "Catlog Heart Icon"
target = "product-card"
path   = "blocks/heart-icon.liquid"

